---

- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    ios_banner:
      banner: login
      text: |
        Nicolas Cage is the
        Tiger King
      state: present

  - name: Add loopback

    ios_interface:
      name: Loopback21
      state: present
  - name: Add ip on loopback interface and description
    ios_config:
      lines:
        - description test test1
        - ip address 172.31.0.1 255.255.255.0
      parents: interface Loopback21
